spring:
  # Redis 配置
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis 数据库索引
    port: 6379 # Redis 端口
#    password
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1  # 连接池最大阻塞时间，负数表示不限制
        max-idle: 10 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小连接数
    timeout: 1000 #连接超时时间（毫秒)
