spring:
  application:
    name: spring-boot-jdbc-template
  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/example?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
server:
  port: 8081